version: '3'
services:
  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: es1
    environment:
      - cluster.name=elk
      - node.name=node1
      - discovery.seed_hosts=es2:9300,es3:9300
      - cluster.initial_master_nodes=es1,es2,es3
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
    volumes:
      - ./elasticsearch:/var/lib/elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk-network    

  es2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: es2
    environment:
      - cluster.name=elk
      - node.name=node2
      - discovery.seed_hosts=es1:9300,es3:9300
      - cluster.initial_master_nodes=es1,es2,es3
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
    volumes:
      - ./elasticsearch:/var/lib/elasticsearch
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      - elk-network

  es3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: es3
    environment:
      - cluster.name=elk
      - node.name=node3
      - discovery.seed_hosts=es1:9300,es2:9300
      - cluster.initial_master_nodes=es1,es2,es3
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
    volumes:
      - ./elasticsearch:/var/lib/elasticsearch
    ports:
      - 9202:9200
      - 9302:9300
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es1:9200
      - ELASTICSEARCH_HOSTS=http://es2:9200
      - ELASTICSEARCH_HOSTS=http://es3:9200
    volumes:
      - ./kibana:/var/lib/kibana
    ports:
      - 5601:5601
    depends_on:
      - es1
      - es2
      - es3
    networks:
      - elk-network

networks:
  elk-network:
